### ISSUE TITLE
There are no User routes.

### ISSUE THREAD

**Issue by dawnpdb** [imrealashu/laravel-multiauth#5]
When I typed 'php artisan route:list' I got all the routes, both admin and users. But, in the 'routes.php' file there are no User routes defined, only the routes with admin are present. Where are the user login/register routes defined in????

**Comment by imrealashu** [comment]
Basically these routes are defined in `/vendor/laravel/framework/src/Illuminate/Routing/Router.php` in `auth` public method. so when we use `Auth::routes()` it registers this routes in the application. 
If you want, you can override these routes by adding each route separately in the route file.

Example
```php
$this->get('login', 'Auth\SomeOtherController@showLoginForm')->name('login');
```
