### ISSUE TITLE
Laravel .env file

### ISSUE THREAD

**Issue by Barnabe22** [imrealashu/laravel-multiauth#7]
How to generate a laravel ".env" file if I have downloaded the application from git. Cause when I have downloaded it, I did not see the ".env" in the folder. It supposes to be in the same range with some files (such as ".env.example", "composer.json", etc..) and also some others folders. I know I'll have the APP_KEY of my application in this ".env" file. So how to generate it in order to have the APP_KEY automatically ? Or will I generate it manually myself by copying and modifying the ".env.example" file to an ".env" file with my own APP_KEY inside ? Your answer will help me.

**Comment by imrealashu** [comment]
Hey @Barnabe22 
Just copy the `.env.example` file and rename it to `.env` file. This is the way everyone follows. The purpose of `.env` file to keep credentials, secret keys and passwords so it's not included in the version control (git). You can generate the APP_KEY using the artisan command `php artisan key:generate`.

**Note:** When you add/delete any keys from the `.env` file make sure, you update the `.env.example` file as well. As we use `.env.example` file as blueprint of what environment variable our application is having.

**Comment by Barnabe22** [comment]
Thank you very much
